package com.fang.cloud.mapper;

import com.fang.cloud.entity.AccessRecord;

public interface AccessRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessRecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessRecord
     *
     * @mbg.generated
     */
    int insert(AccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessRecord
     *
     * @mbg.generated
     */
    int insertSelective(AccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessRecord
     *
     * @mbg.generated
     */
    AccessRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessRecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessRecord record);
}