package com.fang.cloud.mapper;

import com.fang.cloud.entity.AccessLog;

public interface AccessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessLog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessLog
     *
     * @mbg.generated
     */
    int insert(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessLog
     *
     * @mbg.generated
     */
    int insertSelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessLog
     *
     * @mbg.generated
     */
    AccessLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccessLog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessLog record);
}