package com.fang.cloud.mapper;

import com.fang.cloud.entity.Customization;

public interface CustomizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int insert(Customization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int insertSelective(Customization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    Customization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Customization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customization record);
}