package com.fang.cloud.mapper;

import com.fang.cloud.entity.GanJiWebInfo;

public interface GanJiWebInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GanJiWebInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GanJiWebInfo
     *
     * @mbg.generated
     */
    int insert(GanJiWebInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GanJiWebInfo
     *
     * @mbg.generated
     */
    int insertSelective(GanJiWebInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GanJiWebInfo
     *
     * @mbg.generated
     */
    GanJiWebInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GanJiWebInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GanJiWebInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GanJiWebInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GanJiWebInfo record);
}