package com.fang.cloud.entity;

import java.util.Date;

public class AccessLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessLog.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessLog.Url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessLog.MsgContent
     *
     * @mbg.generated
     */
    private String msgcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessLog.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessLog.ID
     *
     * @return the value of AccessLog.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessLog.ID
     *
     * @param id the value for AccessLog.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessLog.Url
     *
     * @return the value of AccessLog.Url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessLog.Url
     *
     * @param url the value for AccessLog.Url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessLog.MsgContent
     *
     * @return the value of AccessLog.MsgContent
     *
     * @mbg.generated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessLog.MsgContent
     *
     * @param msgcontent the value for AccessLog.MsgContent
     *
     * @mbg.generated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessLog.CreateTime
     *
     * @return the value of AccessLog.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessLog.CreateTime
     *
     * @param createtime the value for AccessLog.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}