package com.fang.cloud.entity;

import java.util.Date;

public class AccessRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessRecord.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessRecord.IPAddress
     *
     * @mbg.generated
     */
    private String ipaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessRecord.UrlAddress
     *
     * @mbg.generated
     */
    private String urladdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccessRecord.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessRecord.ID
     *
     * @return the value of AccessRecord.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessRecord.ID
     *
     * @param id the value for AccessRecord.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessRecord.IPAddress
     *
     * @return the value of AccessRecord.IPAddress
     *
     * @mbg.generated
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessRecord.IPAddress
     *
     * @param ipaddress the value for AccessRecord.IPAddress
     *
     * @mbg.generated
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessRecord.UrlAddress
     *
     * @return the value of AccessRecord.UrlAddress
     *
     * @mbg.generated
     */
    public String getUrladdress() {
        return urladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessRecord.UrlAddress
     *
     * @param urladdress the value for AccessRecord.UrlAddress
     *
     * @mbg.generated
     */
    public void setUrladdress(String urladdress) {
        this.urladdress = urladdress == null ? null : urladdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccessRecord.CreateTime
     *
     * @return the value of AccessRecord.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccessRecord.CreateTime
     *
     * @param createtime the value for AccessRecord.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}