package com.fang.cloud.entity;

import java.util.Date;

public class GanJiWebInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.CrawlerUrl
     *
     * @mbg.generated
     */
    private String crawlerurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HousePrice
     *
     * @mbg.generated
     */
    private Double houseprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HouseArea
     *
     * @mbg.generated
     */
    private Integer housearea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HouseDetail
     *
     * @mbg.generated
     */
    private String housedetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HouseDiscribe
     *
     * @mbg.generated
     */
    private String housediscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HouseBusiness
     *
     * @mbg.generated
     */
    private String housebusiness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HouseImage
     *
     * @mbg.generated
     */
    private String houseimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.City
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.Area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.Burg
     *
     * @mbg.generated
     */
    private String burg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.IsEmail
     *
     * @mbg.generated
     */
    private Boolean isemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.ComeFrom
     *
     * @mbg.generated
     */
    private Short comefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.PublishTime
     *
     * @mbg.generated
     */
    private Date publishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.SendMaillTime
     *
     * @mbg.generated
     */
    private Date sendmailltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.IsAnalyze
     *
     * @mbg.generated
     */
    private Short isanalyze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.State
     *
     * @mbg.generated
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HouseIndustry
     *
     * @mbg.generated
     */
    private String houseindustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.HousePriceUnit
     *
     * @mbg.generated
     */
    private String housepriceunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.TransFee
     *
     * @mbg.generated
     */
    private String transfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GanJiWebInfo.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.ID
     *
     * @return the value of GanJiWebInfo.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.ID
     *
     * @param id the value for GanJiWebInfo.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.Title
     *
     * @return the value of GanJiWebInfo.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.Title
     *
     * @param title the value for GanJiWebInfo.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.CrawlerUrl
     *
     * @return the value of GanJiWebInfo.CrawlerUrl
     *
     * @mbg.generated
     */
    public String getCrawlerurl() {
        return crawlerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.CrawlerUrl
     *
     * @param crawlerurl the value for GanJiWebInfo.CrawlerUrl
     *
     * @mbg.generated
     */
    public void setCrawlerurl(String crawlerurl) {
        this.crawlerurl = crawlerurl == null ? null : crawlerurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HousePrice
     *
     * @return the value of GanJiWebInfo.HousePrice
     *
     * @mbg.generated
     */
    public Double getHouseprice() {
        return houseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HousePrice
     *
     * @param houseprice the value for GanJiWebInfo.HousePrice
     *
     * @mbg.generated
     */
    public void setHouseprice(Double houseprice) {
        this.houseprice = houseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HouseArea
     *
     * @return the value of GanJiWebInfo.HouseArea
     *
     * @mbg.generated
     */
    public Integer getHousearea() {
        return housearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HouseArea
     *
     * @param housearea the value for GanJiWebInfo.HouseArea
     *
     * @mbg.generated
     */
    public void setHousearea(Integer housearea) {
        this.housearea = housearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HouseDetail
     *
     * @return the value of GanJiWebInfo.HouseDetail
     *
     * @mbg.generated
     */
    public String getHousedetail() {
        return housedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HouseDetail
     *
     * @param housedetail the value for GanJiWebInfo.HouseDetail
     *
     * @mbg.generated
     */
    public void setHousedetail(String housedetail) {
        this.housedetail = housedetail == null ? null : housedetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HouseDiscribe
     *
     * @return the value of GanJiWebInfo.HouseDiscribe
     *
     * @mbg.generated
     */
    public String getHousediscribe() {
        return housediscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HouseDiscribe
     *
     * @param housediscribe the value for GanJiWebInfo.HouseDiscribe
     *
     * @mbg.generated
     */
    public void setHousediscribe(String housediscribe) {
        this.housediscribe = housediscribe == null ? null : housediscribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HouseBusiness
     *
     * @return the value of GanJiWebInfo.HouseBusiness
     *
     * @mbg.generated
     */
    public String getHousebusiness() {
        return housebusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HouseBusiness
     *
     * @param housebusiness the value for GanJiWebInfo.HouseBusiness
     *
     * @mbg.generated
     */
    public void setHousebusiness(String housebusiness) {
        this.housebusiness = housebusiness == null ? null : housebusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HouseImage
     *
     * @return the value of GanJiWebInfo.HouseImage
     *
     * @mbg.generated
     */
    public String getHouseimage() {
        return houseimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HouseImage
     *
     * @param houseimage the value for GanJiWebInfo.HouseImage
     *
     * @mbg.generated
     */
    public void setHouseimage(String houseimage) {
        this.houseimage = houseimage == null ? null : houseimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.City
     *
     * @return the value of GanJiWebInfo.City
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.City
     *
     * @param city the value for GanJiWebInfo.City
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.Area
     *
     * @return the value of GanJiWebInfo.Area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.Area
     *
     * @param area the value for GanJiWebInfo.Area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.Burg
     *
     * @return the value of GanJiWebInfo.Burg
     *
     * @mbg.generated
     */
    public String getBurg() {
        return burg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.Burg
     *
     * @param burg the value for GanJiWebInfo.Burg
     *
     * @mbg.generated
     */
    public void setBurg(String burg) {
        this.burg = burg == null ? null : burg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.IsEmail
     *
     * @return the value of GanJiWebInfo.IsEmail
     *
     * @mbg.generated
     */
    public Boolean getIsemail() {
        return isemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.IsEmail
     *
     * @param isemail the value for GanJiWebInfo.IsEmail
     *
     * @mbg.generated
     */
    public void setIsemail(Boolean isemail) {
        this.isemail = isemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.ComeFrom
     *
     * @return the value of GanJiWebInfo.ComeFrom
     *
     * @mbg.generated
     */
    public Short getComefrom() {
        return comefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.ComeFrom
     *
     * @param comefrom the value for GanJiWebInfo.ComeFrom
     *
     * @mbg.generated
     */
    public void setComefrom(Short comefrom) {
        this.comefrom = comefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.PublishTime
     *
     * @return the value of GanJiWebInfo.PublishTime
     *
     * @mbg.generated
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.PublishTime
     *
     * @param publishtime the value for GanJiWebInfo.PublishTime
     *
     * @mbg.generated
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.SendMaillTime
     *
     * @return the value of GanJiWebInfo.SendMaillTime
     *
     * @mbg.generated
     */
    public Date getSendmailltime() {
        return sendmailltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.SendMaillTime
     *
     * @param sendmailltime the value for GanJiWebInfo.SendMaillTime
     *
     * @mbg.generated
     */
    public void setSendmailltime(Date sendmailltime) {
        this.sendmailltime = sendmailltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.CreateTime
     *
     * @return the value of GanJiWebInfo.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.CreateTime
     *
     * @param createtime the value for GanJiWebInfo.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.IsAnalyze
     *
     * @return the value of GanJiWebInfo.IsAnalyze
     *
     * @mbg.generated
     */
    public Short getIsanalyze() {
        return isanalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.IsAnalyze
     *
     * @param isanalyze the value for GanJiWebInfo.IsAnalyze
     *
     * @mbg.generated
     */
    public void setIsanalyze(Short isanalyze) {
        this.isanalyze = isanalyze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.State
     *
     * @return the value of GanJiWebInfo.State
     *
     * @mbg.generated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.State
     *
     * @param state the value for GanJiWebInfo.State
     *
     * @mbg.generated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HouseIndustry
     *
     * @return the value of GanJiWebInfo.HouseIndustry
     *
     * @mbg.generated
     */
    public String getHouseindustry() {
        return houseindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HouseIndustry
     *
     * @param houseindustry the value for GanJiWebInfo.HouseIndustry
     *
     * @mbg.generated
     */
    public void setHouseindustry(String houseindustry) {
        this.houseindustry = houseindustry == null ? null : houseindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.HousePriceUnit
     *
     * @return the value of GanJiWebInfo.HousePriceUnit
     *
     * @mbg.generated
     */
    public String getHousepriceunit() {
        return housepriceunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.HousePriceUnit
     *
     * @param housepriceunit the value for GanJiWebInfo.HousePriceUnit
     *
     * @mbg.generated
     */
    public void setHousepriceunit(String housepriceunit) {
        this.housepriceunit = housepriceunit == null ? null : housepriceunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.TransFee
     *
     * @return the value of GanJiWebInfo.TransFee
     *
     * @mbg.generated
     */
    public String getTransfee() {
        return transfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.TransFee
     *
     * @param transfee the value for GanJiWebInfo.TransFee
     *
     * @mbg.generated
     */
    public void setTransfee(String transfee) {
        this.transfee = transfee == null ? null : transfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GanJiWebInfo.Address
     *
     * @return the value of GanJiWebInfo.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GanJiWebInfo.Address
     *
     * @param address the value for GanJiWebInfo.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}