server:
  port: 9000
spring:
  application:
    name: microservice-comsumer
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
myProps:
  accesstoken: "wxapp"
zuul:
  routes:
    baidu:
      path: /fang/**
      url: microservice-provider
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000